feat: docker-compose를 통한 ci/cd 환경 구축

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,5 +1,5 @@
 # todo : 추후에 배포 서버로 변경
-name: 개발 서버 배포
+name: 서버 배포
 
 on:
   push:
@@ -19,7 +19,7 @@ jobs:
           echo "$APPLICATION_PROD_SECRET_YML" > src/main/resources/application-secret.yml
         working-directory: backend
         env:
-          APPLICATION_DEV_SECRET_YML: ${{ secrets.APPLICATION_PROD_SECRET_YML }}
+          APPLICATION_PROD_SECRET_YML: ${{ secrets.APPLICATION_PROD_SECRET_YML }}
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -50,11 +50,22 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
-      - name: Deploy container on EC2
+      - name: Deploy with docker-compose on EC2
         run: |
           ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << EOF
-            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kopmorning:latest
-            docker stop kopmorning || true
-            docker rm kopmorning || true
-            docker run -d --name kopmorning -p 8080:8080 --restart always ${{ secrets.DOCKERHUB_USERNAME }}/kopmorning:latest
+            cd ~/app
+          
+            git pull origin develop || echo "Git pull failed or no repo cloned"
+
+            cat <<EOT > .env
+              $DOCKER_ENV_FILE
+          EOT
+  
+          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kopmorning:latest
+          
+          docker compose down || true
+          
+          docker compose up -d --build
           EOF
+        env:
+          DOCKER_ENV_FILE: ${{ secrets.DOCKER_ENV_FILE }}
